## Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = a.reshape([3,3])

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
b * 10 + 4

array([[14, 24, 34],
       [44, 54, 64],
       [74, 84, 94]])

In [7]:
np.__version__

'1.21.1'

In [8]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x000001BEBC766F40>, toplevel='numpy')>

In [9]:
a = [1,2,3,4]
b = [5,6,7,8]

In [11]:
print(a + b)
print(a * b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)

[ 6  8 10 12]


In [13]:
print(a_array / b_array)

[0.2        0.33333333 0.42857143 0.5       ]


In [14]:
print(a_array * b_array)

[ 5 12 21 32]


## List

In [15]:
v = np.array([1,2,3,4,5])

v.shape

(5,)

In [16]:
m = np.array([[1,2,3], [4,5,6]])

m.shape

(2, 3)

In [17]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [19]:
a = [1,2,3]

type(a)

list

In [20]:
m.size

6

In [21]:
v.size

5

In [23]:
one_dimension = np.array([1,2,3])

two_dimension = np.array([[4,5,6],[7,8,9]])

two_dimension

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
dimensi1 = np.array([1,2,3,4,5,6,7])

dimensi1.shape

(7,)

In [28]:
dimensi2 = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

dimensi2.shape

(3, 3)

In [41]:
dimensi3 = np.array(
[
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
])
 
dimensi3.shape

(4, 4, 4)

In [42]:
ones = np.ones((7,7), dtype=int)

ones

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [44]:
m = np.array([[1,2,3],
            [4,5,6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [48]:
zeros_matrix2 = np.zeros((5,2), dtype="float")

zeros_matrix2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
zeros_matrix3 = np.zeros((5,2,6), dtype="float")

zeros_matrix3

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [51]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])