In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.append(arr, [10,11,12])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.append(arr1, [[10,11,12]], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [28]:
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a,b), axis=1)
c

array([[ 1,  2,  8,  8,  2,  1],
       [ 5,  8, 10,  3,  9,  1]])

In [13]:
x = np.array([[1, 2, 8], [5, 8, 10]])
y = np.array([[8, 2, 1], [3, 9, 1]])
z = np.concatenate((x,y), axis=1)
z

array([[ 1,  2,  8,  8,  2,  1],
       [ 5,  8, 10,  3,  9,  1]])

In [14]:
# Sorting
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Delete elements di array

In [15]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
np.delete(arr, 1, axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## Shape dan size of an array

In [17]:
my_array = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]])

my_array.shape

(3, 2, 4)

In [18]:
my_array.size

24

In [19]:
my_array.ndim

3

## Reshaping an array

In [20]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [21]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
a.shape

(6,)

In [23]:
b.shape

(2, 3)

In [26]:
m = np.arange(2,11)
m

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
m.reshape((3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## Convert 1D to 2D Newaxis

### newaxis

In [30]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [31]:
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [32]:
a.shape

(6,)

In [33]:
a3 = a[:, np.newaxis]
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
a3.shape

(6, 1)

### np.expand_dims

In [35]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [36]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [38]:
c = np.expand_dims(a, axis=0)
c

array([[1, 2, 3, 4, 5, 6]])

In [39]:
c.shape

(1, 6)

## Indexing and Slicing

In [40]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

In [41]:
data[1]

2

In [43]:
data[:4]

array([1, 2, 3, 4])

In [45]:
data[3:]

array([4, 5, 6])

In [46]:
data[-2:]

array([5, 6])

In [49]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [50]:
a[a<5]

array([1, 2, 3, 4])

In [51]:
five_up = a >= 5
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
d = a[a % 2 == 0]
d

array([ 2,  4,  6,  8, 10, 12])

In [53]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [55]:
np.hstack((a, b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 6