## > Exercise 4
1. create a null vector / 1D array of size 10 and update fifth index to 11.
2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays
3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](image/lat1.png)
4. Take a look at the following matrix. Access the [2, 1,1]

# Nomor 1

In [1]:
import numpy as np

x = np.zeros(10)
print(x)
print("Update fifth value to 11")
x[5] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 11
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


# Nomor 2

In [13]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a.shape

(2, 3)

In [12]:
b = a.reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
b.shape

(3, 2)

# Nomor 3

In [16]:
array2 = np.ones((5,5))
array2[1:-1,1:-1] = 0
print(array2)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Nomor 4

In [17]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z[2,1,1]

2

# ASSIGNMENT
1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [83]:
import numpy as np

x = np.arange(0, 3, 0.19).reshape(4,4)

x

array([[0.  , 0.19, 0.38, 0.57],
       [0.76, 0.95, 1.14, 1.33],
       [1.52, 1.71, 1.9 , 2.09],
       [2.28, 2.47, 2.66, 2.85]])

In [43]:
x = np.arange(16).reshape((4, 4))
print("Array pertama:")
x

Array pertama:


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
print("Setelah displit:")
print(np.hsplit(x, [2, 6]))

Setelah displit:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]
